baseURL: https://signetdevelopment.co.uk
languageCode: en-gb
title: Signet Development
theme: vanilla-bootstrap-hugo-theme

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Email
    pre: at-sign
    url: mailto:iain@signetdevelopment.co.uk
    weight: 1
  - name: GitHub
    pre: github
    url: https://github.com/iaingalloway
    weight: 2
  - name: LinkedIn
    pre: linkedin
    url: https://www.linkedin.com/in/iaingalloway/
    weight: 3

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 1200px
  dateFormat: 2006-01-02
  homeText: A UK-based software consultancy.
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
